cgpa calculator

In [2]:
credits=int(input("Enter total no of credits: "))
cgpa=float(int("Enter current cgpa: "))
counter=0
while(True):
    c=int(input("Enter no of credits "))
    counter+=c


Enter total no of credits:  6


ValueError: invalid literal for int() with base 10: 'Enter current cgpa: '

# Assistant
The error occurs because you're trying to convert the string "Enter current cgpa: " to an integer, which isn't possible. When using `input()`, you need to separate the prompt from the conversion.

Would you like me to provide the corrected code?

# User
yes

In [ ]:
# Assistant
credits = int(input("Enter total no of credits: "))
cgpa = float(input("Enter current cgpa: "))  # Changed from int() to input() first, then float()
counter = 0
while(True):
    c = int(input("Enter no of credits: "))
    counter += c

Enter total no of credits:  6


In [1]:
import numpy as np

arr2d = np.arange(16).reshape(4,4)
print(arr2d)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
a=np.hsplit(arr2d,2)
a

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [5]:
a[0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [7]:
np.vsplit(arr2d,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [8]:
np.transpose(a[0])

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13]])

In [9]:
def rfunc(n):
    print(n)
    if n > 0:
        rfunc(n - 1)

In [10]:
rfunc(4)

4
3
2
1
0


In [11]:
print(rfunc(4))

4
3
2
1
0
None


In [17]:
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)
fibonacci(5)

5

In [18]:
fibonacci(5)

5

In [19]:
print(fibonacci(5))

5


In [20]:
print(format('Hello World', '^40'))


              Hello World               


In [21]:
print(format('Hello World', '40'))

Hello World                             


In [22]:
student_name="Arya"
student_address="Delhi"
total_credits=10
current_gpa=5.2
print('Name:', student_name, 'Address:', student_address,'Number of Credits:', total_credits, 'GPA:', current_gpa,
     "hihi")

Name: Arya Address: Delhi Number of Credits: 10 GPA: 5.2 hihi


In [23]:
123+"hi"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [24]:
str(123)+"hi"

'123hi'

In [25]:
3 is 3.0

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/var/folders/ng/6hr92t6j3pvbp9h3swyww2l00000gn/T/ipykernel_34563/344507504.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  3 is 3.0


False

In [26]:
3==3.0

True

In [29]:
#Observe the error
n=0
if n != 0 and 1/n < tolerance:



_IncompleteInputError: incomplete input (3145270138.py, line 4)

In [30]:
d = {'a': 1, 'b': 2, 'c': 3}


In [31]:

d.get('z', 0) # 0 if key doesn't exist


0

In [32]:
d.get('b')

2

In [33]:
d.get('z')

In [34]:
d[z]

NameError: name 'z' is not defined

In [35]:
d.pop('b')

2

In [36]:
d.popitem()

('c', 3)

In [37]:
d.clear()

In [38]:
d={1:2}
d[3]=d.pop(1)

In [39]:
d

{3: 2}

In [40]:
t=(91,2)
type(t)

tuple

In [41]:
t=(92)
type(t)

int

In [42]:
t=[1,2,]
type(t)

list

In [43]:
t[2]

IndexError: list index out of range