**<center><h3>Data Operations with Numpy Assignment Problem</h3></center>**

In [1]:
import numpy as np

---
**<h4>Question 1:** Create a function that generate a null vector of size N containing a certain value at specified position.</h4>

- For example, you passed `vector_size = 5`, `val = 2`, and `pos = 2`.

- The value returned will be `[0. 0. 2. 0. 0.]`.

<details>

**<summary>Hint:</summary>**

- Initialize vector with the zeros of specified vector size. You can use the numpy's function here.

- Pass the index value of specified position and assign it the passed value. 

- Display the result.

</details>

In [13]:
def createNull(vector_size=None, val=None, pos=None):
    if pos==None :
        return
    if vector_size==None:
        return
    if val==None:
        val=0
    vector=np.zeros(vector_size)
    vector[pos]=val
    return vector

In [14]:
createNull(vector_size=5, val=2, pos=2)

array([0., 0., 2., 0., 0.])

---
**<h4>Question 2:** Create a function that generate a vector of size N with values ranging from A to B.</h4>

- For example, you passed `vector_size = 11`, `start_val = 0`, and `end_val = 2`.

- The value returned will be `[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]`.

<details>

**<summary>Hint:</summary>**

- You can achieve this question by using the numpy's linspace functionality.

</details>

In [26]:
def vectorBetween(vector_size=None, start_val=None, end_val=None):
    if vector_size==None:
        return
    if start_val==None:
        start_val=0
    if end_val==None:
        print("No end val so we cannot complete this program")
        return
    vector=np.linspace(start_val,end_val,vector_size)
    print(vector)

In [30]:
vectorBetween(vector_size=11, start_val=0, end_val=2)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


---
**<h4>Question 3:** Create a function that performs the normalization over the matrix as shown below in the example.</h4>

- Create a 2-dimensional matrix of size N X M.
  - Let's say you created a matrix of 3 X 3.
    - `|0 1 2|`
    - `|3 4 5|`
    - `|6 7 8|`

- Subtract the matrix with the mean of the rows of the matrix.
  - The mean of the rows of the matrix came out to be `1, 4, 7`.
    - `|0 1 2| - |1|`
    - `|3 4 5| - |4|`
    - `|6 7 8| - |7|`

- Divide the whole matrix by the twice size of the max value present in the matrix.
  - The max value of the matrix elements came out to be 1.
    - `|-1 0 1| ÷ (2*1)`
    - `|-1 0 1| ÷ (2*1)`
    - `|-1 0 1| ÷ (2*1)`

- Display the final result.
    - `|-0.5  0   0.5|`
    - `|-0.5  0   0.5|`
    - `|-0.5  0   0.5|`

<details>

**<summary>Hint:</summary>**

- Pass an array of elements along with the matrix dimensions of nrows and ncols.

- Reshape the array with the specified matrix dimensions. You can use numpy's reshape functionality.

- Get the mean of the matrix in a row-wise fashion. You may need to reshape the mean matrix in a column-wise structure.

- Subtract the elements of the matrix with the mean matrix.

- Extract the maximum value present in the matrix and multiply it with the number 2.

- Divide the subtracted matrix with the extracted maximum value and display the result.

</details>

In [92]:
def matrixNormalization(input_matrix=None, nrows=None, ncols=None):
    if nrows==None or ncols==None:
        return
    if input_matrix is None:
        input_matrix=np.zeros(nrows*ncols)
    input_matrix=input_matrix.reshape(nrows,ncols).astype(float)#int to int division will give u 0
    mean_list=list()
    for i in range(nrows):
        mean_list.append(np.mean(input_matrix[i, :]))
    for i in range(nrows):
        for a in range(ncols):
             input_matrix[i, a] -= mean_list[i]
    max_val=input_matrix.max()*2
    for i in range(nrows):
        for a in range(ncols):
             input_matrix[i, a]/=max_val
        print(input_matrix[i])

In [93]:
matrixNormalization(input_matrix=np.arange(0, 9), nrows=3, ncols=3)

[-0.5  0.   0.5]
[-0.5  0.   0.5]
[-0.5  0.   0.5]


---
**<h4>Question 4:** Create a function that generates a matrix of shape N X M with random values in a decreasing order.</h4>

- For example, you passed 9 random values such as:
  -  `[0.83086063, 0.00536904, 0.58981977, 0.76704028, 0.55501003, 0.91354796, 0.57879962, 0.76508311, 0.66402454]`.

- The value returned will be:
    - `|0.83086063 0.00536904 0.58981977|`
    - `|0.76704028 0.55501003 0.91354796|`
    - `|0.57879962 0.76508311 0.66402454|`

<details>

**<summary>Hint:</summary>**

- Initialize a vector with random values of specified size in the function.

- Sort the vector in descending order using sorted() method. You may require to convert the sorted value to an array again.

- Reshape the sorted vector using the reshape functionality present in the numpy package.

- Display the final output.

</details>

In [ ]:
def randMatrix(vectorsize=None, nrows=None, ncols=None):
    

In [ ]:
randMatrix(vectorsize=9, nrows=3, ncols=3)

---
**<h4>Question 5:** Create a function that generates an array ranging from A to B and perform inverse-sign on inclusive values.</h4>

- For example, you passed `[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]`.

- The final output will be `[-5,  4,  3,  2,  1,  0, -1, -2, -3,  4]`.

<details>

**<summary>Hint:</summary>**

- Initialize an array of specified size using start and stop position.

- If array>start and array<stop-1, then array = array * -1.

- You can also use conditional operation, mathematical operation and assigning operation in combination.

- If not sure, refer to the solution sheet.

</details>

In [ ]:
def inclusiveInverse(arrstart=None, arrstop=None):
  # Put your code here...

In [ ]:
inclusiveInverse(arrstart=-5, arrstop=5)

---
**<h4>Question 6:** Creates a function that returns a N size array on replacing max & min values with a specified value in reverse order.</h4>

- For example, you passed `arrlow = 1`, `arrhigh = 10`, `arrsize = 10`, `replacemaxby = 2`, and `replaceminby = 4`.

- The array generated with the specified values is `[5 8 8 3 3 1 7 4 4 5]`.

- After replacing the max and min value the array becomes `[5 2 8 3 3 4 7 4 4 5]`.

- On sorting the array in reverse direction (decreasing order) it becomes `[8 7 5 5 4 4 4 3 3 2]`. 

<details>

**<summary>Hint:</summary>**

- Initiate a random array of specified size along with the low and high values.

- For this you can use numpy's random integer functionality.

- Replacing max and min value in an array with a specified value.

- For the above step you can use numpy's argmax functionality.

- Reverse the modified array after replacing values using sorted() function of python.

</details>

In [ ]:
def randReplaceReverse(arrlow=None, arrhigh=None, arrsize=None, replacemaxby=None, replaceminby=None):
  # Put your code here...

In [ ]:
randReplaceReverse(arrlow=1, arrhigh=10, arrsize=10, replacemaxby=2, replaceminby=4)

---
**<h4>Question 7:** Create a function that returns the euclidean distance between two arrays.</h4>

- For example, you passed two arrays such as : `[1, 2, 3, 4, 5]` and `[4, 5, 6, 7, 8]`

- The returned output will be `6.708`.

<details>

**<summary>Hint:</summary>**

- The formula that is used to calculate euclidean distance is $\sqrt {\sum _{i=1}^{n}  \left( q_{i}-p_{i}\right)^2 } $ where p and q are two points in Euclidean n-space.

- There are many ways to achieve this question. You can use numpy's linalg class file to directly compute the distance.

- Typecast the input to numpy array as it is the requirement for norm() functionality of linalg class file.

- Return the final output.

</details>

In [ ]:
def calculateEuclidean(arr1=None, arr2=None):
  # Put your code here...

In [ ]:
calculateEuclidean(arr1, arr2)

---
**<h4>Question 8:** Create a function that generates an $N_1$ X $N_2$ matrix filled with a chessboard pattern.</h4>

- For example, you passed `N1 = 8`, and `N2 = 8`.

- The output will be as shown below:

<center>|0 1 0 1 0 1 0 1|</center>
<center>|1 0 1 0 1 0 1 0|</center>
<center>|0 1 0 1 0 1 0 1|</center>
<center>|1 0 1 0 1 0 1 0|</center>
<center>|0 1 0 1 0 1 0 1|</center>
<center>|1 0 1 0 1 0 1 0|</center>
<center>|0 1 0 1 0 1 0 1|</center>
<center>|1 0 1 0 1 0 1 0|</center>

<details>

**<summary>Hint:</summary>**

- Initialize a matrix with the specified dimensions.

- You can use the numpy's zeros() functionality to do this task.

- Then for even rows and odd columns using indexing and striding place value = 1.

- For odd rows and even columns using indexing and striding place value = 1.

- Display the result.

</details>

In [ ]:
def createChessMatrix(N1=None, N2=None):
  # Put your code here...

In [ ]:
createChessMatrix(N1=10, N2=10)

---
**<h4>Question 9:** Create a function that displays the number of weekdays and dates ranging from Date A to Date B.</h4>

- For example, you passed `start_date = 1994-04` and `end_date = 1994-05`.

- The returned output will be: `Total Weekdays: 21`

- `[1994-04-01, 1994-04-02, 1994-04-03, 1994-04-04, 1994-04-05, 1994-04-06, 1994-04-07, 1994-04-08, 1994-04-09, 1994-04-10, 1994-04-11, 1994-04-12, 1994-04-13, 1994-04-14, 1994-04-15, 1994-04-16, 1994-04-17, 1994-04-18, 1994-04-19, 1994-04-20, 1994-04-21, 1994-04-22, 1994-04-23, 1994-04-24, 1994-04-25, 1994-04-26, 1994-04-27, 1994-04-28, 1994-04-29, ,1994-04-30]`

<details>

**<summary>Hint:</summary>**

- You can use numpy's busday_count() functionality to estimate total weekday frequency.

- Next, you need to generate dates ranging from Date A to Date B.

- This can be achieved using the help of numpy's arange() functionality.

- **Note:** Make sure the dtype is set to datetime64[D].

- Display out the final result.

</details>

In [ ]:
def generateDates(start_date=None, end_date=None):
  # Put your code here...

In [ ]:
generateDates(start_date='1994-04', end_date='1994-05')

---
**<h4>Question 10:** Create a function that performs padding of size S with value P over the numpy array.</h4>

- For example, you passed `arr = None`, `noarrshape = (3, 3)`, `pad_size = 2`, `pad_val = 7`.

- The returned output will be:

<center>|7 7 7 7 7 7 7|</center>
<center>|7 7 7 7 7 7 7|</center>
<center>|7 7 1 1 1 7 7|</center>
<center>|7 7 1 1 1 7 7|</center>
<center>|7 7 1 1 1 7 7|</center>
<center>|7 7 7 7 7 7 7|</center>
<center>|7 7 7 7 7 7 7|</center>


<details>

**<summary>Hint:</summary>**

- Check if the passed array exists or not.

- If the array is none, then generate a default array with ones of specified shape.

- Return the padded array of size S with the padded value P.

- To achieve this, you can use numpy's pad() functionality.

- Next, if the array is passed, then perform padding using pad() and return it.

</details>

In [ ]:
def padArray(arr=None, noarrshape=None, pad_size=None, pad_val=None):
  # Put your code here...

In [ ]:
padArray(arr=None, noarrshape=(3, 3), pad_size=2, pad_val=7)