In [2]:
#to work with numerics in python and arrays
#linear alegebra in python

In [3]:
l1=[1,2,3]

In [4]:
l1

[1, 2, 3]

In [8]:
import numpy

In [14]:
numpy.array(l1) #if numpy was not imported it will show error

array([1, 2, 3])

In [15]:
import numpy as np #alias for numpy

In [19]:
np.array(l1) #1 row multi column->vector

array([1, 2, 3])

In [17]:
#if numpy is not successfully executed then you have to install it explicitly in juptier nb environment using code "conda install numpy".

In [18]:
#to identify array->array() is written.

In [20]:
#arange-generates array works same as range a part of numpy

In [21]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [23]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [24]:
#zeros and ones->arrays containing 0s and 1s in floating values

In [25]:
np.zeros(4)

array([0., 0., 0., 0.])

In [26]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.zeros((7,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
#linspace **important**
#returns evenly spaced numbers over a specified interval
#eg np.linspace(x,y,z) this generates z numbers from x to y x and y both included

In [32]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [33]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [58]:
np.linspace(0,10,50).reshape(5,10)

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
         1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
         3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
         5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
         7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
         9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

In [34]:
#eye->creates an identity matrix

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
#in python there are 3 types of generating random numbers
#rand(),randn(),randint() they are methods

In [39]:
#rand creates array with random numbers bw 0 and 1 with 1 excluded has uniform distribution

In [40]:
np.random.rand(2)

array([0.32128407, 0.2069865 ])

In [41]:
np.random.rand(2,3)

array([[0.30365142, 0.11371442, 0.4615963 ],
       [0.28081139, 0.13086267, 0.31805696]])

In [42]:
#randn is normal distribution,standard deviation is eq and mean falls to 0 can have negative values as well 

In [43]:
np.random.randn(5,5)

array([[ 1.32552638,  0.67886842, -1.39091205,  0.37978265, -1.07132421],
       [ 0.57461693, -0.31857984, -1.01271654, -1.08480895,  0.39322041],
       [-0.42551847,  0.99908135,  2.055813  ,  0.2211775 ,  0.95739965],
       [ 0.81388157, -0.59141944,  0.18585225, -0.96715739,  0.95665522],
       [-1.04524554, -0.43800032,  0.99181216, -0.690595  ,  0.00960794]])

In [44]:
np.random.randn(2)

array([0.97787104, 0.07903227])

In [45]:
#randint gives random integers with randint(x,y,z) includes x excludes y gives z elements

In [46]:
np.random.randint(1,100)

3

In [47]:
np.random.randint(1,1000,50)

array([920, 242, 640, 382, 401, 906, 227, 431, 210,  90, 451, 139, 105,
       731, 655, 196, 833, 690, 707, 673, 865, 915, 902, 799, 762, 787,
       289, 830, 374, 959, 257, 985,  83, 584, 139, 552, 780, 525, 184,
       606, 102, 123, 894,  95, 717,  61, 533, 430, 106, 666], dtype=int32)

In [48]:
#Array attributes and methods

In [20]:
arr=np.arange(25)
ranarr=np.random.randint(0,50,10)

In [51]:
arr,ranarr

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]),
 array([22, 46, 34, 21, 38, 23,  0, 43, 10, 47], dtype=int32))

In [56]:
#Reshape:returns an array containing the same data with a new shape eg 1 d array to matrix but the restriction is if matrix size is bigger than the elements present in 1d array

In [59]:
arr.reshape(5,5) #here it converted arr which was 1d array to a 5,5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
import numpy as np
import time
size_of_vec=1000000

def pure_python_version():
    time_python=time.time()
    my_list1=range(size_of_vec)
    my_list2=range(size_of_vec)
    sum_list=[my_list1[i]+my_list2[i] for i in range(len(my_list1))]
    return time.time()-time_python
def numpy_version():
    time_numpy=time.time()
    my_arr1=np.arange(size_of_vec)
    my_arr2=np.arange(size_of_vec)
    sum_array=my_arr1+my_arr2
    print(type(sum_array))
    return time.time()-time_numpy

python_time=pure_python_version()
numpy_time=numpy_version()

print("Pure Python version {:0.4f}".format(python_time))
print("Numpy version {:0.4f}".format(numpy_time))
print("Numpy is in this example{:0.4} times faster!".format(python_time/numpy_time))

<class 'numpy.ndarray'>
Pure Python version 0.4433
Numpy version 0.0093
Numpy is in this example47.88 times faster!


In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr.max()

np.int64(24)

In [23]:
arr.dtype()

TypeError: 'numpy.dtypes.Int64DType' object is not callable

In [24]:
arr.dtype

dtype('int64')

In [25]:
arr.max()

np.int64(24)

In [26]:
arr.max

<function ndarray.max>

In [27]:
arr.argmax()

np.int64(24)

In [28]:
arr.max().item()

24

In [54]:
arr.argmax()
arr.argmin()
#for index of max number and min number

np.int64(0)

In [30]:
#NumPy operations

In [32]:
#ARITHMETIC

In [33]:
import numpy as np

In [34]:
arr=np.arange(0,10)

In [35]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
type(arr)

numpy.ndarray

In [37]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [47]:
arr/arr #warning NAN stands for not a number

C:\Users\VANSHIKA\AppData\Local\Temp\ipykernel_123820\3167388759.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr #warning NAN stands for not a number


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [41]:
arr+arr-3*arr

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [45]:
1/arr #not nan but infinity

C:\Users\VANSHIKA\AppData\Local\Temp\ipykernel_123820\1550252181.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr #not nan but infinity


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [46]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [48]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [49]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [50]:
np.max(arr)

np.int64(9)

In [51]:
arr.max()

np.int64(9)

In [55]:
np.log(arr)

C:\Users\VANSHIKA\AppData\Local\Temp\ipykernel_123820\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [56]:
np.sin(arr)
# instead except for max and arr.min() all have to be written as np.func(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [1]:
import numpy as np

# Numpy Indexing and Selection

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8] #arr[index]

np.int64(8)

In [5]:
arr[1:5]

array([1, 2, 3, 4])

# Broadcasting

In [7]:
#setting a value with index range(Broadcasting)

In [8]:
arr[1:5]=100

In [9]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
arr=np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Slicing

In [12]:
slice_of_an_array=arr[0:6]

In [13]:
slice_of_an_array

array([0, 1, 2, 3, 4, 5])

In [14]:
#change slice
slice_of_an_array[:]=99

In [19]:
slice_of_an_array #changes will be in original array too

array([99, 99, 99, 99, 99, 99])

In [16]:
#[:]->starting till end including both
#[:x]->from start till x-1
#[x:]->from x till end(inlcuded)

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
#to avoid changes in original create copy

In [20]:
arr_copy=arr.copy()

In [21]:
arr[9]=199

In [22]:
arr

array([ 99,  99,  99,  99,  99,  99,   6,   7,   8, 199,  10])

In [23]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing a 2d array(matrices)

In [24]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[1]

array([20, 25, 30])

In [27]:
#format is arr_2d[row][col] or arr_2d[row,col]

In [28]:
arr_2d[1][0]

np.int64(20)

In [29]:
arr_2d[2][1]

np.int64(40)

In [30]:
arr_2d[0,2]

np.int64(15)

In [31]:
#2d array slicing

In [33]:
arr_2d[:2,1:] #0th and 1st row will be returned while 1st to 2nd column

array([[10, 15],
       [25, 30]])

In [36]:
arr_2d[1:,0:2]

array([[20, 25],
       [35, 40]])

# Fancy indexing

In [39]:
a=np.zeros((10,10))

In [40]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
#length of array

In [42]:
alen=a.shape[1]

In [43]:
alen

10

In [47]:
#set up array
for i in range(alen):
    a[i]=i

In [48]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [51]:
a[[0,1,3],:] #0,1,3 rows of a till end column are returned

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [53]:
a[[0,1,3],:][:,[0,2]] #of the above first two columns are returned

array([[0., 0.],
       [1., 1.],
       [3., 3.]])

In [54]:
a[[6,4,7,8],:]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])